export OPENAI_API_KEY="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"
export GPT_MODEL='gpt-4o-mini’
